### ISSUE TITLE
Encoding problem for WWW2018

### ISSUE THREAD

**Issue by lmedini** [sympozer/datasets#1]
Non-ANSI characters are erroneously encoded. Issue seems general to the dataset.

Examples:

http://sympozer.liris.cnrs.fr/www2018/#/person/J%C7%B8r%EF%BF%BD%EF%BF%BDme%20David/https%253A%252F%252Fw3id.org%252Fscholarlydata%252Fperson%252Fme-david

http://sympozer.liris.cnrs.fr/www2018/#/organization/Link%EF%BF%BDping%20University/https%253A%252F%252Fw3id.org%252Fscholarlydata%252Forganisation%252Fping-university

**Comment by anuzzolese** [comment]
This can be easily fixed by providing the proper charset encoding as input argument to cLODg.

**Comment by pchampin** [comment]
Seems to be fixed. Closing
