### ISSUE TITLE
Erroneous ID for a person in WWW2018

### ISSUE THREAD

**Issue by lmedini** [sympozer/datasets#2]
When looking for "Jean-Philippe Mag**" (cf. previous issue), and clicking on the link to his description on the app, the view http://sympozer.liris.cnrs.fr/www2018/#/person/Jean-Philippe%20Magu%EF%BF%BD/https%253A%252F%252Fw3id.org%252Fscholarlydata%252Fperson%252F describes someone else (Enrique Amig**). And this person is not searchable in the dataset.

**Comment by pchampin** [comment]
Seems fixed. Closing
