### ISSUE TITLE
Author list incorrect

### ISSUE THREAD

**Issue by infoxiao** [sympozer/datasets#7]
The correct list:

Web-Based VR Experiments Powered by the Crowd. Xiao Ma, Megan Cackett, Leslie Park, Eric Chien, Mor Naaman.

**Comment by infoxiao** [comment]
Pinging the status thanks!

**Comment by pchampin** [comment]
Seen [from the app](https://www2018.thewebconf.org/app/#/publication/Web-Based%2520VR%2520Experiments%2520Powered%2520by%2520the%2520Crowd/https%253A%252F%252Fw3id.org%252Fscholarlydata%252Finproceedings%252Fwww-research-2018-crowdsourcing-608)
the list seems to be still incorrect...

**Comment by infoxiao** [comment]
Can anyone give me write access? I can create a pull request changing the publications.ttl directly..
@sympozer @pchampin

**Comment by infoxiao** [comment]
Created a pull request -- https://github.com/sympozer/datasets/pull/8

Please review! Thanks. @pchampin @sympozer

**Comment by lmedini** [comment]
Merged, thanks for the job @infoxiao
